# Generated by Django 4.2.2 on 2024-11-18 08:56

import django_countries.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("users", "0002_user_token"),
    ]

    operations = [
        migrations.AddField(
            model_name="user",
            name="country",
            field=django_countries.fields.CountryField(blank=True, max_length=50, null=True),
        ),
    ]
